### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by aammjian** [a54552239/pearProject#19]
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'lru-cache'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\vue\pearProject-master\node_modules\_@vue_cli-shar
ed-utils@3.8.0@@vue\cli-shared-utils\lib\env.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by aammjian** [comment]
删掉整个module，重新安装后完成
