### ISSUE TITLE
Failed to execute 'setAttribute' on 'Element': '`' is not a valid attribute name.

### ISSUE THREAD

**Issue by HYY-yu** [a54552239/pearProject#24]
点击团队成员 》 某个成员 》 任务安排。
系统报错：

chunk-vendors.cc66b7f0.js:79 DOMException: Failed to execute 'setAttribute' on 'Element': '`' is not a valid attribute name.
    at Wr (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:51049)
    at Br (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:50786)
    at Array.Ir (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:50376)
    at M (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:45153)
    at m (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:44516)
    at p (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:44333)
    at f (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:43924)
    at _ (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:44909)
    at f (https://static.vilson.online/pearProject/static/js/chunk-vendors.cc66b7f0.js:79:44039)

**Comment by a54552239** [comment]
已修复 https://github.com/a54552239/pearProject/commit/66896ca24f32677a065ecc577f0d4b52d1817281
