### ISSUE TITLE
npm run serve 页面console报错

### ISSUE THREAD

**Issue by wtlihao** [a54552239/pearProject#60]
ndex.js?72c8:5 Uncaught TypeError: Object(...) is not a function
    at eval (index.js?72c8:5:1)
    at Module../node_modules/_ant-design-vue@2.2.8@ant-design-vue/es/vc-resize-observer/index.js (app.js:8104:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (index.js?3502:1:1)
    at Module../node_modules/_ant-design-vue@2.2.8@ant-design-vue/es/affix/index.js (app.js:4084:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (components.js?e52b:1:1)
    at Module../node_modules/_ant-design-vue@2.2.8@ant-design-vue/es/components.js (app.js:4624:1)

**Comment by 839536** [comment]
Thank you. Your email is received and will be handled  as soon as possible.

**Comment by wtlihao** [comment]
> Thank you. Your email is received and will be handled  as soon as possible.

请问怎么解决这个问题？

**Comment by wtlihao** [comment]
![image](https://user-images.githubusercontent.com/30258468/167995073-126a4a53-4e94-48d0-b17a-84bc5046c760.png)

**Comment by wtlihao** [comment]
上面的console调试 看到这个index.js里面有报错

**Comment by a54552239** [comment]
将 package.json 的 "ant-design-vue": "lastest" 修改为 "ant-design-vue": "^1.7.8"

**Comment by a54552239** [comment]
或拉取本项目最新代码
